# Generated by Django 2.2.10 on 2020-10-29 12:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wibsite_url',
            field=models.CharField(blank=True, help_text='لا تنسى وضع https://', max_length=255, null=True, verbose_name='رابط الموقع'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='الصورة الشخصية '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
